### ISSUE TITLE
Having elements before / after list

### ISSUE THREAD

**Issue by pakastin** [pakastin/redom#24]
Will investigate this in the next version.

**Comment by maciejhirsz** [comment]
I was thinking about it before. One possible solution for a list without a root element playing nicely with neighbouring child nodes is to store it's own `first` and `last` node references, so whenever you start the traverse, you go from the list's `first` instead of parent's `firstChild`, and iterate till `traverse === list.last`.

This, however, only works if the list always has elements. A potential workaround would be store not the `first` element of the list, but the `previous` node in the parent (if any).

**Comment by pakastin** [comment]
One solution would also be to use empty `document.createTextNode('')` as a placeholder before the first and after the last item..

**Comment by pakastin** [comment]
I've tried it and it doesn't affect CSS layout in any way (like `document.createTextNode('\n')` does..)..

**Comment by maciejhirsz** [comment]
That should work! Actually, you only need a placeholder at the start of the list and store an element count to know how many elements to remove on the next update.

**Comment by pakastin** [comment]
Of course, yeah :)
